### ISSUE TITLE
Firefox + dom.webcomponents.enabled=true rendering oddity

### ISSUE THREAD

**Issue by ktiedt** [Polymer/polymer-element-catalog#138]
While I realize this may entirely be Firefox not correctly supporting something just yet, I thought it worthwhile to bring it up.

I was recently testing Firefox performance with Polymer and was testing with this feature on vs off to see if coercing users to enable the flag was a sufficient solution (primarily 0.5 stuff at this point).

So when using the Polymer Elements Catalog as a test of this feature, I noticed that the renders in a mobile layout all the time, and some text stuff does not quite line up correctly.

Figured I'd let the experts determine if it was a polymer related bug or just some missing CSS that Firefox needs.

**Comment by arthurevans** [comment]
Sorry for the delayed response here. I believe this is an issue with the polyfills. See: 

https://github.com/webcomponents/webcomponentsjs/issues/289

I've added a note about this to the browser compat. section of the Polymer docs:

https://github.com/Polymer/docs/pull/1298/files#diff-889ebef33036d0efbbf7c032a27a17f0R66

(Merged but not published yet.)

Since this isn't specific to the catalog, I'm going to close the bug here.
